name: Update Anime Lists

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:

  anime-lists:

    name: Update Anime List
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: python3 -m pip install --pre -r scripts/requirements.txt

      - name: Update current Anime Lists in Readme
        run: python3 scripts/animelist.py

      - name: Update current Favourites in Readme
        run: python3 scripts/favourites.py

      - name: Commit & Push
        uses: actions-js/push@main
        with:
          message: update latest projects
          branch: main