---
name: Update Anime Lists
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install python dependencies
        run: python3 -m pip install --pre -r scripts/requirements.txt
      - name: Update Favourites
        run: python3 scripts/favourites.py
      - name: Update Anime List
        run: python3 scripts/animelist.py
