name: project-automation
on:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  update_projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests 
      - run: python python/api.py