name: Metrics
on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_stars: yes
          plugin_stars_limit: 4
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: media/metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: shaderLab, HLSL
          plugin_languages_details: bytes-size, percentage
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
          filename: media/metrics-steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198116350170"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0