name: Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  push:
    branches:
      - main # Hier den Namen deiner Haupt-Branch angeben

jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          username: crimsonshade