---
name: Update Birthday
on: 
  schedule:
    - cron: "1 0 22 3 *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Update Anime List
        run: python3 scripts/birthday.py
      - name: Commit and Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "😼 ~ Arra Arra ~ 😼"